spring:
  application:
    name: Websocket

  redis:
    # redis所在主机地址
    host: 127.0.0.1
    # redis所在端口
    port: 6379
    # 连接密码
    password: 123456
    # 选择的数据库索引，默认0
    database: 2
    # 连接最大空闲时间
    timeout: 3000
    # Lettuce连接池配置
    lettuce:
      pool:
        # 允许最大连接数，默认8
        max-active: 8
        # 最大空闲连接数，默认8
        max-idle: 8
        # 最小空闲连接数，默认0
        min-idle: 0
        # 最长阻塞等待时间，默认-1无限制
        max-wait: -1

  datasource:
    hikari:
      # 连接池最大连接数，默认是 10
      maximum-pool-size: 60
      # 链接超时时间，默认 30000(30 秒)
      connection-timeout: 60000
      # 空闲连接存活最大时间，默认 600000(10 分钟)
      idle-timeout: 60000
      # 连接将被测试活动的最大时间量
      validation-timeout: 3000
      # 此属性控制池中连接的最长生命周期，值 0 表示无限生命周期，默认 1800000(30 分钟)
      max-lifetime: 600000
      # 连接到数据库时等待的最长时间(秒)
      login-timeout: 5
      # 池中维护的最小空闲连接数
      minimum-idle: 10
    # 连接mysql的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    # mysql服务地址 格式：jdbc:mysql://{mysql服务所在IP地址}:{mysql服务所在端口}/{数据库名称}?{一些参数}
    url: jdbc:mysql://127.0.0.1:3306/ws_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&jdbcCompliantTruncation=false&allowMultiQueries=true
    # 使用的用户名
    username: root
    # 用户名对应的密码
    password: 123456


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id

server:
  port: 8080


jwt:
  #  过期时间（单位：ms）
  expire: 604800000
  #  密钥
  secret: koishikoishikisskisslovelylovelykoishikoishikoishi