spring:
  application:
    name: RedisTemplate

  redis:
    # redis所在主机地址
    host: 127.0.0.1
    # redis所在端口
    port: 6379
    # 连接密码
    password: 123456
    # 选择的数据库索引，默认0
    database: 1
    # 连接最大空闲时间
    timeout: 3000
    # Lettuce连接池配置
    lettuce:
      pool:
        # 允许最大连接数，默认8
        max-active: 8
        # 最大空闲连接数，默认8
        max-idle: 8
        # 最小空闲连接数，默认0
        min-idle: 0
        # 最长阻塞等待时间，默认-1无限制
        max-wait: -1
#    jedis:

server:
  port: 8080
